#!/usr/bin/env bash
#cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_TOOLCHAIN_FILE="cmake/toolchain-arm-none-eabi.cmake" -DAPPLICATION="LoRaMac" -DSUB_PROJECT="classA" -DMODULATION="LORA" -DBOARD="SmartbinL4" -DACTIVE_REGION="LORAMAC_REGION_EU868" ..
#cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_TOOLCHAIN_FILE="cmake/toolchain-arm-none-eabi.cmake" -DAPPLICATION="LoRaMac" -DSUB_PROJECT="classA" -DMODULATION="LORA" -DBOARD="PressureSensor" -DACTIVE_REGION="LORAMAC_REGION_EU868" ..
#cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_TOOLCHAIN_FILE="cmake/toolchain-arm-none-eabi.cmake" -DAPPLICATION="LoRaMac" -DSUB_PROJECT="" -DMODULATION="periodic-uplink-lpp" -DBOARD="SmartWaste" -DACTIVE_REGION="LORAMAC_REGION_EU868" ..

#cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCLASSB_ENABLED=ON  -DAPPLICATION="LoRaMac" -DSUB_PROJECT="classA" -DCMAKE_TOOLCHAIN_FILE="cmake/toolchain-arm-none-eabi.cmake" -DBOARD="L496xx" -DMBED_RADIO_SHIELD=SX1276MB1LAS -DACTIVE_REGION="LORAMAC_REGION_EU868" --graphviz=dependency.dot ..
#cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCLASSB_ENABLED=ON  -DAPPLICATION="LoRaMac" -DSUB_PROJECT="periodic-uplink-lpp" -DCMAKE_TOOLCHAIN_FILE="cmake/toolchain-arm-none-eabi.cmake" -DBOARD="SmartWaste" -DMBED_RADIO_SHIELD=SX1276MB1LAS -DULTRASOUND_SENSOR=DUAL_SENSOR -DUSE_ACCELEROMETER=ON ..

#cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCLASSB_ENABLED=ON  -DAPPLICATION="LoRaMac" -DSUB_PROJECT="periodic-uplink-lpp" -DCMAKE_TOOLCHAIN_FILE="cmake/toolchain-arm-none-eabi.cmake" -DBOARD="PressureSensor" -DMBED_RADIO_SHIELD=SX1276MB1LAS ..
#cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCLASSB_ENABLED=ON  -DAPPLICATION="LoRaMac" -DSUB_PROJECT="classA" -DCMAKE_TOOLCHAIN_FILE="cmake/toolchain-arm-none-eabi.cmake" -DBOARD="PressureSensor" -DMBED_RADIO_SHIELD=SX1276MB1LAS --graphviz=dependency.dot ..
#cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCLASSB_ENABLED=ON  -DAPPLICATION="LoRaMac" -DSUB_PROJECT="classA" -DCMAKE_TOOLCHAIN_FILE="cmake/toolchain-arm-none-eabi.cmake" -DBOARD="B-L072Z-LRWAN1" -DMBED_RADIO_SHIELD=SX1276MB1LAS -DACTIVE_REGION="LORAMAC_REGION_EU868" --graphviz=dependency.dot ..

# L496xx
#cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCLASSB_ENABLED=ON  -DAPPLICATION="LoRaMac" -DSUB_PROJECT="classA" -DCMAKE_TOOLCHAIN_FILE="cmake/toolchain-arm-none-eabi.cmake" -DBOARD="L496xx" -DMBED_RADIO_SHIELD=SX1276MB1LAS -DACTIVE_REGION="LORAMAC_REGION_EU868" --graphviz=dependency.dot ..

cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCLASSB_ENABLED=ON  -DAPPLICATION="LoRaMac" -DSUB_PROJECT="periodic-uplink-lpp" -DCMAKE_TOOLCHAIN_FILE="cmake/toolchain-arm-none-eabi.cmake" -DBOARD="L496xx" -DMBED_RADIO_SHIELD=SX1276MB1LAS -DACTIVE_REGION="LORAMAC_REGION_EU868" --graphviz=dependency.dot ..
#cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCLASSB_ENABLED=ON  -DAPPLICATION="LoRaMac" -DSUB_PROJECT="periodic-uplink-lpp" -DCMAKE_TOOLCHAIN_FILE="cmake/toolchain-arm-none-eabi.cmake" -DBOARD="L496xx" -DNUCLEO144=ON -DMBED_RADIO_SHIELD=SX1276MB1LAS -DACTIVE_REGION="LORAMAC_REGION_EU868" --graphviz=dependency.dot ..

#cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCLASSB_ENABLED=ON  -DAPPLICATION="porting_test" -DCMAKE_TOOLCHAIN_FILE="cmake/toolchain-arm-none-eabi.cmake" -DBOARD="L496xx" -DNUCLEO144=ON -DMBED_RADIO_SHIELD=SX1276MB1LAS -DACTIVE_REGION="LORAMAC_REGION_EU868" --graphviz=dependency.dot ..
#cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCLASSB_ENABLED=ON  -DAPPLICATION="porting_test" -DCMAKE_TOOLCHAIN_FILE="cmake/toolchain-arm-none-eabi.cmake" -DBOARD="L496xx" -DMBED_RADIO_SHIELD=SX1276MB1LAS -DACTIVE_REGION="LORAMAC_REGION_EU868" --graphviz=dependency.dot ..

#cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCLASSB_ENABLED=ON  -DAPPLICATION="tx-cw" -DCMAKE_TOOLCHAIN_FILE="cmake/toolchain-arm-none-eabi.cmake" -DBOARD="L496xx" -DMBED_RADIO_SHIELD=SX1276MB1LAS -DACTIVE_REGION="LORAMAC_REGION_EU868" --graphviz=dependency.dot ..
#cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCLASSB_ENABLED=ON  -DAPPLICATION="ping-pong" -DCMAKE_TOOLCHAIN_FILE="cmake/toolchain-arm-none-eabi.cmake" -DBOARD="L496xx" -DMBED_RADIO_SHIELD=SX1276MB1LAS -DACTIVE_REGION="LORAMAC_REGION_EU868" --graphviz=dependency.dot ..

dot -Tpng -o dependency.png dependency.dot
make -j4 && mv ./compile_commands.json ..
